export { default as LandingPage } from "@/pages/landingPage.jsx";
export { default as LoginPage } from "@/pages/loginPage.jsx";
export { default as SignUpPage } from "@/pages/signupPage.jsx";
export { default as DashboardPage } from "@/pages/dashboardPage.jsx";
export { default as ProfilePage } from "@/pages/profilePage.jsx";
export { default as RegisterHospitalPage } from "@/pages/registerHospitalPage.jsx";
export { default as EquipmentPage } from "@/pages/equipmentPage.jsx";
export { default as MaintenancePage } from "@/pages/maintenancePage.jsx";
export { default as SettingsPage } from "@/pages/settingsPage.jsx";
